- name: copy rabbitmq environment file
  become: yes
  template:
    src: rabbitmq.env.j2
    dest: /etc/babili/environments/rabbitmq.env
  notify:
    - restart rabbitmq

- name: ensure rabbitmq data container exists
  become: yes
  docker_container:
    name: rabbitmq-data
    image: tianon/true
    state: present
    volumes:
    - /var/lib/rabbitmq

- name: copy rabbitmq systemd unit
  become: yes
  template:
    src: rabbitmq.service.j2
    dest: /etc/systemd/system/rabbitmq.service
  notify:
    - reload systemd units
    - restart rabbitmq
    - auto-start rabbitmq

- name: pull image
  raw: sudo docker pull {{ docker_image }}
  changed_when: docker_pull.stdout.find("Downloaded newer image") != -1
  register: docker_pull

- name: check if image is up to date
  command: /bin/true
  when: docker_pull.changed
  notify:
    - restart rabbitmq
