- name: copy pusher environment file
  become: yes
  template:
    src: pusher.env.j2
    dest: /etc/babili/environments/pusher.env
  notify:
    - restart pusher

- name: ensure pusher data container exists
  become: yes
  docker_container:
    name: pusher-data
    image: tianon/true
    state: present
    volumes:
    - /data

- name: copy pusher systemd unit
  become: yes
  template:
    src: pusher.service.j2
    dest: /etc/systemd/system/pusher.service
  notify:
    - reload systemd units
    - restart pusher
    - auto-start pusher

- name: pull image
  raw: sudo docker pull {{ docker_image }}
  changed_when: docker_pull.stdout.find("Downloaded newer image") != -1
  register: docker_pull

- name: check if image is up to date
  command: /bin/true
  when: docker_pull.changed
  notify:
    - restart pusher
